language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: AqoALnFN7Z3atYCB8hWTU7l/52zmg2+0POyx8C3uWdnl6mJowuuKq+cI0ARF2x6r086VOCvcuW+cWmAPxfmiUAa5uN/w5D3KDcarVrmgT5RziYTAl6I1eH9E/pPxvS7E5eyjtx5N1nDw119BZMxM9J63mM+eSgYQdLw2J1I7LoliDxW18sFY0OVRF/iXtDL1AS/QdUwI3ezatWpKSKuIrFqr0lEtnobxsyHvAhDmej+eb1aIUB9Ux/vhpihUS6+HmYX24vyjdCL1ZWFjCHc9pdIfokJNFCwiOtimNyQ1LFrnVhQfmzBEqavSQsjMoybG2sjRGx18uSP7wnRgQyy582zUvpvzyG+KBhQg5xsc/ia95rv3qKxNknJgpctDGXATWC8qvcQyRnk7c4Z0FCEP7rOjB4Cmv53gEVD0cUAIcDUWsMhFKvTPy0ca1IE+IHGZEr/ZP+MibS2ZEpyrnn06+wQnnMl6KAe9YvHjaWiF2a0dT/pyfB/QN/tARFgIQHuWktUe3eR81IvyFW11yBa6eNb/oFYN1tFxPDDl+P8N54AKaIFnnddlWoDTERoedghE/OBPtttgMdsUttp1oCIh9pkr6Oyj0dW3PJ+8pJTs7wsaYbd+QZ21VmCOHcLO76YrWXO/G+nFmd1A7nQK/4R3ntQ/1NBIfRWRB/HMN5g9YOQ=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: VfYW3lzWiRzERYlee/kA5Nnf0D6eZTlkqyiUYFM5UFiP9SQpLz/jzpJBJD1tkWig4PearW5JHdprIF8pgmTi9vA2Qwj9yq+KLgGUwWsT8LSPoly0/F+qf6fVlKxjZwbM4lZA3aB8kLEyp0xkm1yqYNGq90OTmdTPRnOBY9rkn2qr9UNWNg4Zmx2Yy4jnttDjZ0WbEn4JhtvsuGtT6vW2P65AzoWjNICW7CwBT/dbA4XW8W/OSOc0ivLfcC4ggT1RBqBIUdUudRaVBRr1j0U9fh6yHgklf98yBlZF68yKoi75jGluazB3XwMFHF1Xho4h69ZD29xWlv+McxmnHMNHdEyyIGZklBfIX93yMpvESnOFLrGTf4r5KNry9A1MwqN/4SLwvywMzDHXQuI1SZ9N5IVoLDR/d7W84So2yG/OmCNiibHLIbrf3sU1rCV7hY4Wuv9mYJmRtbKRYc7FgobOe19QYuAqppxN4+fMQmcVzhzpPAmZA9ZqtNiaqzGIydJkJXaXXdDUQgnr9hSxdXqIDuk1LOzMNje3ZDprke6FSQic9QhmjzJ5Bt3/Wic20suX0b2oFifMUDrMMpcVGPkbVay1MvIu5cJDUyeZhBKMF+L+iLYchgTzdH5kQOUYm9gQJzaYjkU7jBsk+foyl5iyBcZg1u93KH7zx1rGXUdvl0s=
  - secure: yZJg/Dl3Zu5+qxBH9AkzwKWoxo9HkmlPxc0cEtzQzA0U73ZelCD180akSJDh7Z4dz5hZJ3KZ3rDE7Qi9TTTi5Vnmaas8kD7O5TbiXnWm3zqUO67jzV3BPaPFmuWaHIxgAXQlbO1BM8L62x8YTEjOXxYcuLrB8ogof7C4Mxd3ep8JDVRo20M3QcxVPWGbx1KFjIYaZzLg+gRjWOFQJx+Z7yWXkLHnchTgod6HQM92eJAbLdws1MZyRXr0btuU9T8boFI1x11Fp1FWRodEfRSnKJrMGkGXGZagEHg8HI8853npb55GJpGap+Kf9NVPacICz7k8gSb2zCQkaqDWgQVnamybHjCIjdh/TrMOvcnFBmE9dALD57BBLahfiIJVsdQzjGWiHuMB2DejLnKFyI+/vOG1phI6zXjgDjM6oTgseoVcES5u8dfRCdXxrS12bemUdNkKGqaLSFJKCtReJLwcHIta3Xx5sym71QWhj4uzVwRsYB6BUJiJkbnjcHK89VGoF3jeb5LwlItdgmvj85cNou8aJeH+HTCv0DG2wa42IVqLTxKRWEnbK4SykdBkQDeb03sP/tK2AjAusagDBOoLe6n4DXNobB4DLbL5OM8l1c0N/ANFsisrjlaHgcysdjbpGo5TQBtrkyDbrvWt7nc+NVLe1vfyMDsfZk5O9dhL8KU=
  - secure: qheP2HxmqBy91Q/vG4wryeWTZQ2B8jrRk7zaVsuWYx5ln3KzPKXqaUXuSi1y/EPRR4XhZ1bBS2vsvRSqKqUlGAmkhVZ2wkjdex71g4mkABrUzwqrM08fHKdMkBNRvFuuNfzjo+V3rjviXsJL3oczOb3vrAbPyvUxQ4QTeXteCGSofMRRKkSMoJHNHJSHdB9yl9+81AjCQDBAUHLxsyV50Dl4Ewoeu5bDtccDPU+OuRRY+MjLkadSzqsH5tF3DDEEn22116R0oobkaI/Tj5grlQ9vsKFEwi4gch9meiwh4WSSxFGBe4U6kUAWYK2EFK4hjpcBzkIJZ0UBaovxi9T4js5L5VL8ibf/kxOtjLOzVsdYvQSIUMIovszVUgCKk0IyT6OWa+idETmmIX3WiOtsjZwvoZC7pqqRq8He+xlWiEBSu00m/heEfbCB7coja4JsUAWMfrdGKVaCj8mbH8lUqYVG3qGlbRm4WkkjstubZe9KjEwoaWIEhU9UirzFxBps4Uc+JfhxFWadBDHhhDV3zwIGeBg+BMJyJnmyY26QOd4J4iPTjvF2an+M7jIwW3BXfsKExKL6UuX28pf2I4G8dDvhVWHCk7Lix7hGsXKAvo8bgOD4oYyiUthxT07K4U7R9C1UaXvxiGd5pHlVHoEUo4zc0mQEgmN0+ihkpiLlUE0=
before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-judge-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
jobs:
  include:
  - stage: build and deploy
    script:
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and deploy
  if: branch = master
