language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: AqoALnFN7Z3atYCB8hWTU7l/52zmg2+0POyx8C3uWdnl6mJowuuKq+cI0ARF2x6r086VOCvcuW+cWmAPxfmiUAa5uN/w5D3KDcarVrmgT5RziYTAl6I1eH9E/pPxvS7E5eyjtx5N1nDw119BZMxM9J63mM+eSgYQdLw2J1I7LoliDxW18sFY0OVRF/iXtDL1AS/QdUwI3ezatWpKSKuIrFqr0lEtnobxsyHvAhDmej+eb1aIUB9Ux/vhpihUS6+HmYX24vyjdCL1ZWFjCHc9pdIfokJNFCwiOtimNyQ1LFrnVhQfmzBEqavSQsjMoybG2sjRGx18uSP7wnRgQyy582zUvpvzyG+KBhQg5xsc/ia95rv3qKxNknJgpctDGXATWC8qvcQyRnk7c4Z0FCEP7rOjB4Cmv53gEVD0cUAIcDUWsMhFKvTPy0ca1IE+IHGZEr/ZP+MibS2ZEpyrnn06+wQnnMl6KAe9YvHjaWiF2a0dT/pyfB/QN/tARFgIQHuWktUe3eR81IvyFW11yBa6eNb/oFYN1tFxPDDl+P8N54AKaIFnnddlWoDTERoedghE/OBPtttgMdsUttp1oCIh9pkr6Oyj0dW3PJ+8pJTs7wsaYbd+QZ21VmCOHcLO76YrWXO/G+nFmd1A7nQK/4R3ntQ/1NBIfRWRB/HMN5g9YOQ=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: FGC2AtAxASj+TANQucxcpFeu8nUD/WhUCt8f3nSb63SFoAZb0GBFednWBfQ+i5q3KG2qfCKD8EV742czY9njFeHPZUpeMxhzQjg1vqypfClIRZR48VrZuEiO0Qe5VTvTohn4z4iV40N8mR2cIrWUqdD0JZoHbSZwvdigt76Cjpx1YStwjE59Ej+LE9A0fhPfQad0+iKXn3cHcHEXsNfDzQAhdWI/N9/hQMC1hnl4icvpJtqnv2i4Pun0z+4n/nDJbeE6dqGjFhrxY+EeHG0xQ1C93gh9qw04rE0VkrJpp4pIrjJzua5hFf1p7VwgI2tiXO1w6eS9fMOgwMix1jHm61GSMIu/kNmWnat8MNTHpiFnXfTAwKydJYspCWvqmT0+ysOH9sLqNEfxesQZmLr6hm+2KFqur3GyJlc0mqugIvj31Wimr7Mbez0+PlB26iJzp/aLE62+ssjbIdHxE6V3tuHzvyI3khZzvsT3t+JZIWDrsAvqLo8FgNBBOlleglv6JGH21rpAR8y3a2R1E/XYBfj2i74CsFJWcIOWwjgEDBWplXqVDYLc3vPdtOysPp8jU79pQEP8q3biHo3RmTW1UjQYelPTLUWARp1pNUYVed6h0Yumrb+nAv4WRytVUDepkBhK6jbcMl8NRqj2ZM03fBbutKMRpEToX0PMTiUBkAA=
  - secure: dBiRp76pwlvEUvF7jBCkl8U7/FpTqXlkN2nr81Z2AkNvEyMVAek7NyCNbrCFf3cJ6dLyBEdipPXasCIVYUdEqnhrLVCOUXtfHGTOvAYYS+IsfKQDr3BewEGAEPzTSqORWFwoDPDGfgGzs0jY0Nlxh+bABFhhc/z6qpMoVTxH8inOvUinZo7c9APh27e8MriMYtQqTrcVb/ySGt5hfg7r4Omk+DSCq96amixGsHLEAI2Y2ePf3W8KzhftLTNBmEvs3g0Tw/M3M35YzUqcRsxKdCsX7w7MkryVZ3HIy8gXTqIBOxETQzenlDA/HB5nXbk8z9dwAhgpkSjmX0z+8aXLIG2EFAdXedORq2ru8uBazU3taTqIY/iS14oV/M7h1gTS81/HITd1SuktSKa1TCKk1xWnzcprDp/6HdbmQ7lE//lSIQfeDWK5moYjJo7uGTHXSJloXEFPoel6L7tfSSjvvEzpp+yl6+7/+EEfzYDCrGOh3VoIf6UoA9nfDPbvpm/ZK5x/OWWeT0KC/BWGZXFwLl664+zB54YZQL5b9ZqFHsI2DSCk0IqnqO1ZijmsJP/SAbPkBhf9pjhkMA5eCRLU4McmlElPhVwqf9Ejy8nuNCRzWgqx4cAFaFVHfD5QC09rHAlr1dpsmS+sBP9JPEzPnoJyLscS/5/94wOsoDEkumw=
  - secure: ibdPLZWXWxpbHD/C65VPO3Ir1zLiQH1A0+cYD7CGdws5mjW+l7/o7ehYpxwJ2ImltYZm5Ykl0y5DzZ+7xW3DL19UUgxkAoSczUXrf+bbzVHgEXEE2nNHiVVVutWQXLcPneCSRgCFjfEGOE4Pc/ai3oMyjCQ8GKwCeGdUAanJdyf9kiX1x3y4uddHvfmQNUUzsQQMswpNUgZdmbM7ROEBizYrjt77B5Fu+zc+p1Bj4J7SWTaX3IXCaWtrOXF5ocF3yGeQFN4bltpS1Qei+vLdVKZplSia/+0ZQBCSRkPG4pG0eVv+4n6reyke8Bhz6PdVg4Z2XH93pcb85KO0R5reut3WVy79uD/srLQAz1qOR6GEWtC5R8jiyLWRy3rd3DMOVv5SkcZAbyDTNhqb5aqS79kHqAgLTvgW871EJIiHIn1LcgbgoP+ZJ2C65Xp8DiuguXAXINUvQ8PuXD8S94Qk98Gm2cochQ2C7SYjnQf74S3ji0oVKUNVKo6RIqvca1Z9RUpXTcl/yyfL+4jKqmi7cAloNFIGi/xjmBMmF44XiYj6vYLucilciofuHS2Umzz+rgJddJBT4DNT12XW/dCjGSuKwWdal2XL7BfPTD9q91NzSySOIVrdiHmwqJeVzJL4pXquRqP0d2sFAUlK0qzV0ux76HMuerB6PrF0dGaBEzk=
before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-judge-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
jobs:
  include:
  - stage: build and deploy
    script:
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and deploy
  if: branch = master
